from __future__ import annotations

from typing import Optional

from compas.geometry import Cylinder
from compas.geometry import Frame
from compas.geometry import Line
from compas.geometry import Transformation
from compas_brep import Brep

from compas_timber.fabrication import Drilling

from .anchor import AnchorKind
from .fastener import Fastener
from .fastener import FastenerPart


class Dowel(FastenerPart):
    """
    Descibre a cylindrical dowel that can be used as part of a fastener.

    Parameters
    ----------
    diameter: float
        The diameter of the dowel.
    length: float
        The length of the dowel.

    Attributes
    ----------
    diameter: float
        The diameter of the dowel.
    length: float
        The length of the dowel.
    centerline: :class:`~compas.geometry.Line`
        The centerline of the dowel, in local coordinates.
    blank_geometry: :class:`~compas.geometry.Cylinder`
        The blank geometry of the dowel, in local coordinates.
    """

    @property
    def __data__(self):
        return {
            "diameter": self.diameter,
            "length": self.length,
        }

    def __init__(self, diameter: float, length: float, placement_frame: Optional[Frame] = None, **kwargs):
        super().__init__(frame=placement_frame, **kwargs)
        self.diameter = diameter
        self.length = length

    @property
    def centerline(self) -> Line:
        sp = self._local_frame.point
        ep = self._local_frame.point + (-self._local_frame.zaxis * self.length)
        return Line(sp, ep)

    @property
    def _local_frame(self) -> Frame:
        return Frame.worldXY()

    @property
    def blank_geometry(self) -> Cylinder:
        cylinder_frame = Frame(self._local_frame.point, self._local_frame.xaxis, self._local_frame.yaxis)
        cylinder = Cylinder(self.diameter / 2, self.length, cylinder_frame)
        cylinder.frame.point += self._local_frame.zaxis * (-self.length / 2)
        return cylinder

    def compute_elementgeometry(self, include_features: bool = False) -> Brep:
        cylinder = self.blank_geometry
        cyl_brep = Brep.from_cylinder(cylinder)
        return cyl_brep

    def apply_fastening_features(self, elements: list) -> None:
        """Apply the fabrication features generated by this dowel to the connected timber elements.

        The dowel is assumed to be a cylindrical hole in the connected timber elements. The hole is centered on the
        dowel's placement frame and has the same diameter as the dowel.

        Parameters
        ----------
        elements : list[:class:`~compas_model.elements.Element`]
            The timber elements connected by this fastener.
        """
        xform = self.modeltransformation
        for element in elements:
            drill_line = self.centerline
            drill_line.transform(xform)
            drilling = Drilling.from_line_and_element(drill_line, element, self.diameter)
            element.add_feature(drilling)


class DowelFastener(Fastener):
    """
    A fastener consisitng of one dowel per anchor, placed on the axis a joint expososes.

    Parameters
    ----------
    diameter: float
        The diameter of the dowel.
    length: float
        The length of the dowel.

    Attributes
    ----------
    ACCEPTS: :class:`~compas_timber.fasteners.AnchorKind`
        The kind of anchor this fastener binds to.
    """

    ACCEPTS = AnchorKind.AXIS

    @property
    def __data__(self):
        data = super().__data__
        data["diameter"] = self.diameter
        data["length"] = self.length
        return data

    def __init__(self, diameter: float, length: float, **kwargs):
        super().__init__(**kwargs)
        self.diameter = diameter
        self.length = length

    def bind(self, anchors: list) -> DowelFastener:
        """Binds the `DowelFastener` to a set of anchors. Stages one `DowelPart` at each.

        Parameters
        ----------
        anchors: list of :class:`~compas_timber.fasteners.FastenerAnchor`
            The anchors to placte th plate at. Every anchor must be of the kinf this fastener accepts.

        Returns
        -------
        "class:`~compas_timber.fasteners.DowelFastener`
            The fatener itself, dor chaining.

        Raises
        ------
        ValueError
            If any of the anchors are not of the kind this fastener accepts.

        """
        anchors = list(anchors)
        wrong = [anchor for anchor in anchors if anchor.kind is not self.ACCEPTS]
        if wrong:
            raise ValueError("{} accepts {} anchors, got {}.".format(type(self).__name__, self.ACCEPTS, [anchor.kind for anchor in wrong]))

        # one dowel per anchor
        for anchor in anchors:
            dowel = Dowel(self.diameter, self.length)
            dowel.transform(Transformation.from_frame(anchor.frame))
            self.add_part(dowel)
        return self
