from __future__ import annotations

from typing import Optional

from compas.geometry import Cylinder
from compas.geometry import Frame
from compas.geometry import Line
from compas.geometry import Transformation
from compas_brep import Brep

from compas_timber.fabrication import Drilling

from .anchor import AnchorKind
from .fastener import Fastener
from .fastener import FastenerPart
from .fastener import FastenerSystem


class Dowel(FastenerPart):
    """
    Descibre a cylindrical dowel that can be used as part of a fastener.

    Parameters
    ----------
    diameter: float
        The diameter of the dowel.
    length: float
        The length of the dowel.

    Attributes
    ----------
    diameter: float
        The diameter of the dowel.
    length: float
        The length of the dowel.
    centerline: :class:`~compas.geometry.Line`
        The centerline of the dowel, in local coordinates.
    blank_geometry: :class:`~compas.geometry.Cylinder`
        The blank geometry of the dowel, in local coordinates.
    """

    @property
    def __data__(self):
        return {
            "diameter": self.diameter,
            "length": self.length,
            "placement_frame": self.placement_frame,
            "element_guids": self.element_guids,
        }

    def __init__(self, diameter: float, length: float, placement_frame: Optional[Frame] = None, **kwargs):
        super().__init__(frame=placement_frame, **kwargs)
        self.diameter = diameter
        self.length = length

    @property
    def centerline(self) -> Line:
        sp = self._local_frame.point
        ep = self._local_frame.point + (-self._local_frame.zaxis * self.length)
        return Line(sp, ep)

    @property
    def drill_line(self) -> Line:
        drill_line = self.centerline.copy()
        xform = self.modeltransformation
        drill_line.transform(xform)
        return drill_line

    @property
    def _local_frame(self) -> Frame:
        return Frame.worldXY()

    @property
    def blank_geometry(self) -> Cylinder:
        cylinder_frame = Frame(self._local_frame.point, self._local_frame.xaxis, self._local_frame.yaxis)
        cylinder = Cylinder(self.diameter / 2, self.length, cylinder_frame)
        cylinder.frame.point += self._local_frame.zaxis * (-self.length / 2)
        return cylinder

    def compute_elementgeometry(self, include_features: bool = False) -> Brep:
        cylinder = self.blank_geometry
        cyl_brep = Brep.from_cylinder(cylinder)
        return cyl_brep

    def apply_fastening_features(self) -> None:
        """Apply the fabrication features generated by this dowel to :attr:`elements`.

        The dowel is assumed to be a cylindrical hole in its elements. The hole is centered on the dowel's placement
        frame and has the same diameter as the dowel.
        """
        xform = self.modeltransformation
        for element in self.elements:
            drill_line = self.centerline
            drill_line.transform(xform)
            drilling = Drilling.from_line_and_element(drill_line, element, self.diameter)
            element.add_feature(drilling)
            self.applied_features.append(drilling)


class DowelFastenerSystem(FastenerSystem):
    """
    A fastener system placing one dowel per anchor, on the axis a joint exposes.

    Parameters
    ----------
    diameter: float
        The diameter of the dowel.
    length: float
        The length of the dowel.

    Attributes
    ----------
    ACCEPTS: list of :class:`~compas_timber.fasteners.AnchorKind`
        The kinds of anchor this system binds to.
    """

    ACCEPTS = [AnchorKind.AXIS]

    @property
    def __data__(self):
        return {
            "diameter": self.diameter,
            "length": self.length,
        }

    def __init__(self, diameter: float, length: float, **kwargs):
        super().__init__(**kwargs)
        self.diameter = diameter
        self.length = length

    def bind(self, anchors: list) -> Fastener:
        """Build a fastener staging one dowel at each of the given anchors.

        Parameters
        ----------
        anchors: list of :class:`~compas_timber.fasteners.FastenerAnchor`
            The anchors to place the dowel at. Every anchor must be of a kind this system accepts.

        Returns
        -------
        :class:`~compas_timber.elements.Fastener`
            A new fastener, its dowels staged and positioned, ready to be added to a model.

        Raises
        ------
        ValueError
            If any of the anchors are not of a kind this system accepts.

        """
        anchors = self._validate_anchors(anchors)

        # one dowel per anchor
        fastener = Fastener()
        for anchor in anchors:
            dowel = Dowel(self.diameter, self.length)
            dowel.transform(Transformation.from_frame(anchor.frame))
            dowel.elements = list(anchor.elements)
            fastener.add_part(dowel)
        return fastener
