from __future__ import annotations

import uuid
from typing import Optional

from compas.geometry import Frame
from compas.geometry import Transformation


class Fastener:
    """
    This is the fastener and it is composed by parts.

    The fastener has to create the interactions between the elements.

    The fastener should be as independent as possible.

    Each part tells how the beam should be machined.

    It should never interact with a joint but it dies have one as reference.
    """

    def __init__(self, main_part, frame: Frame = Frame.worldXY(), target_frames: Optional[list[Frame]] = None):
        self.frame = Frame.worldXY()
        self.main_part = main_part
        self.interactions = []  # list of interactions tuple (child, parent)
        self.parts = [main_part]
        self.target_frames = target_frames
        self.guid = uuid.uuid4()

    @property
    def target_frames(self) -> list[Frame]:
        return self._target_frames

    @target_frames.setter
    def target_frames(self, value: Optional[list[Frame]]):
        if value is None:
            self._target_frames = []
            return
        if not isinstance(value, list):
            raise ValueError("target_frames should be a list of Frames.")
        else:
            self._target_frames = value

    @property
    def geometry(self):
        geometries = []
        for part in self.parts:
            part_geometry = part.geometry
            geometries.append(part_geometry)
        return geometries

    def copy(self) -> Fastener:
        new_fastener = Fastener(self.main_part)
        new_fastener.frame = self.frame.copy()
        new_fastener.parts = [part.copy() for part in self.parts]
        new_fastener.interactions = list(self.interactions)
        new_fastener.target_frames = list(self.target_frames)
        return new_fastener

    def add_part(self, part):
        """
        Add a single part to the fastener. The parent of the part is the main_part.

        Parameters
        ----------
        part : Part
            The part to be added to the fastener.

        """
        self.parts.append(part)
        self.interactions.append((part, self.main_part))

    def add_child_part(self, part, parent):
        """
        Add a single part to the fastener.

        Parameters
        ----------

        part : Part
            The part to be added to the fastener.

        parent : list[Part]
            The parent of the part added.
        """
        self.parts.append(part)
        self.interactions.append((part, parent))

    def get_parent(self, part):
        """Return the parent of a specific part."""
        for interaction in self.interactions:
            if interaction[0] == part:
                return interaction[1]
        return None

    def get_children(self, part):
        """Return the children of the specific part."""
        children = []
        for interaction in self.interactions:
            if interaction[1] == part:
                children.append(interaction[0])
        return children

    def get_fastener_instances(self) -> list[Fastener]:
        """
        Get the instances of this fastener at the target frames specified.

        This method is called by `compas_timber.model` and return the fastener instances that are part of the timber model.

        Returns
        -------
        list[Fastener]
            The list of fastener instances at the target frames.
        """

        fastener_instances = []
        for target_frame in self.target_frames:
            # copy and transform the fastener
            fastener_instance = self.copy()
            fastener_instance.frame = target_frame
            fastener_instance.target_frames = None
            transformation = Transformation.from_frame_to_frame(self.frame, target_frame)
            fastener_instance._update_parts_frame(transformation)

            fastener_instances.append(fastener_instance)
        return fastener_instances

    def _update_parts_frame(self, transformation):
        for part in self.parts:
            part.frame = part.frame.transformed(transformation)

    def apply_features(self, elements):
        """
        Apply the processings features generated by the parts to the elements.

        Parameters
        ----------
        elements : list[Element]
            The elements to which the features of the parts will be applied.

        """
        for part in self.parts:
            part.apply_features(elements)
