"""End-to-end protobuf round-trip of a whole TimberModel.

The point of these tests is the claim that a fully featured model -- beams,
plates, panels, joints, processings -- survives a protobuf round-trip without
losing data.
"""

import json

import pytest
from compas.data import json_dumps
from compas.data import json_loads
from compas.geometry import Line
from compas.geometry import Point
from compas.geometry import Polyline
from compas_pb import pb_dump_bts
from compas_pb import pb_load_bts

from compas_timber.connections import LMiterJoint
from compas_timber.connections import TButtJoint
from compas_timber.elements import Beam
from compas_timber.elements import LayerDefinition
from compas_timber.elements import LayerStructure
from compas_timber.elements import Panel
from compas_timber.elements import Plate
from compas_timber.fabrication import Drilling
from compas_timber.model import TimberModel


@pytest.fixture(autouse=True)
def load_serializers():
    import compas_timber.proto.conversions  # noqa: F401


@pytest.fixture
def model():
    """A model with beams, a plate, a layered panel and two kinds of joint."""
    model = TimberModel()
    beam_a = Beam.from_centerline(Line(Point(0, 0, 0), Point(3000, 0, 0)), width=100.0, height=200.0)
    beam_b = Beam.from_centerline(Line(Point(3000, 0, 0), Point(3000, 3000, 0)), width=100.0, height=200.0)
    beam_c = Beam.from_centerline(Line(Point(1500, 0, 0), Point(1500, 2000, 0)), width=80.0, height=160.0)
    for beam in (beam_a, beam_b, beam_c):
        model.add_element(beam)

    outline = Polyline([Point(0, 0, 0), Point(1000, 0, 0), Point(1000, 1000, 0), Point(0, 1000, 0), Point(0, 0, 0)])
    model.add_element(Plate.from_outline_thickness(outline, 20.0))

    panel = Panel.from_outline_thickness(outline, 50.0)
    panel.layer_structure = LayerStructure([LayerDefinition("exterior", 10.0), LayerDefinition("core", 40.0)])
    model.add_element(panel)

    LMiterJoint.create(model, beam_a, beam_b)
    TButtJoint.create(model, beam_c, beam_a)
    model.process_joinery()
    return model


def roundtrip(model):
    return pb_load_bts(pb_dump_bts(model))


def test_model_roundtrip_is_lossless(model):
    """The whole model compares equal to itself after a protobuf round-trip.

    Compared as parsed compas JSON with minimal=True: guids of nested value
    geometry are regenerated by compas_pb's converters, and parsing rather than
    string comparison keeps an int widening to a float on a proto `double`
    field from reading as a difference.
    """
    other = roundtrip(model)
    assert json.loads(json_dumps(other, minimal=True)) == json.loads(json_dumps(model, minimal=True))


def test_model_element_count_and_types_preserved(model):
    other = roundtrip(model)
    before = sorted(type(e).__name__ for e in model.elements())
    after = sorted(type(e).__name__ for e in other.elements())
    assert before == after
    assert "Beam" in after and "Plate" in after and "Panel" in after


def test_model_element_guids_preserved(model):
    """Joints reference elements by guid, so guids must survive."""
    other = roundtrip(model)
    assert sorted(str(e.guid) for e in other.elements()) == sorted(str(e.guid) for e in model.elements())


def test_model_joints_preserved(model):
    other = roundtrip(model)
    before = sorted(type(j).__name__ for j in model.joints)
    after = sorted(type(j).__name__ for j in other.joints)
    assert before == after
    assert set(after) == {"LMiterJoint", "TButtJoint"}


def test_model_joints_still_reference_their_elements(model):
    """The graph is intact: every joint's element guids resolve in the model."""
    other = roundtrip(model)
    element_guids = {str(e.guid) for e in other.elements()}
    for joint in other.joints:
        assert element_guids.issuperset(set(joint.element_guids))


def test_model_non_joinery_features_preserved(model):
    """Features the user applied travel with their element.

    Joinery features are deliberately excluded: TimberElement.__data__ filters
    on `is_joinery`, because process_joinery() regenerates them. compas' own
    JSON serialization drops them for the same reason, so the protobuf
    round-trip matches it rather than inventing extra state.
    """
    beam = next(e for e in model.elements() if type(e).__name__ == "Beam")
    beam.add_features(Drilling(start_x=100.0, start_y=50.0, diameter=8.0, is_joinery=False))

    other = roundtrip(model)
    drillings = [f for e in other.elements() for f in e.features if isinstance(f, Drilling)]
    assert len(drillings) == 1
    assert drillings[0].diameter == 8.0
    assert str(drillings[0].guid) == str(beam.features[-1].guid)


def test_joinery_features_are_excluded_like_compas_json(model):
    """The protobuf round-trip loses exactly what compas' own JSON loses."""
    via_proto = sum(len(e.features) for e in roundtrip(model).elements())
    via_json = sum(len(e.features) for e in json_loads(json_dumps(model)).elements())
    assert via_proto == via_json


def test_model_panel_layer_structure_preserved(model):
    other = roundtrip(model)
    panel = next(e for e in other.elements() if type(e).__name__ == "Panel")
    assert [d.name for d in panel.layer_structure.layer_defs] == ["exterior", "core"]


def test_model_tree_and_graph_preserved(model):
    """compas_model's tree/graph are plain dicts in __data__ and carried as AnyData."""
    other = roundtrip(model)
    assert other.__data__["tree"] == model.__data__["tree"]
    assert other.__data__["graph"] == model.__data__["graph"]


def test_empty_model_roundtrip():
    model = TimberModel()
    other = roundtrip(model)
    assert len(list(other.elements())) == 0
    assert len(list(other.joints)) == 0
