"""End-to-end protobuf round-trip tests for individual timber elements."""

import json

import pytest
from compas.data import json_dumps
from compas.geometry import Frame
from compas.geometry import Line
from compas.geometry import Point
from compas.geometry import Polyline
from compas_pb import pb_dump_bts
from compas_pb import pb_load_bts

from compas_timber.elements import Beam
from compas_timber.elements import LayerDefinition
from compas_timber.elements import LayerStructure
from compas_timber.elements import Panel
from compas_timber.elements import Plate
from compas_timber.panel_features import Opening


@pytest.fixture(autouse=True)
def load_serializers():
    import compas_timber.proto.data  # noqa: F401


def roundtrip(obj):
    return pb_load_bts(pb_dump_bts(obj))


def assert_lossless(obj):
    """Round-trip `obj` and assert nothing in its __data__, guid or name was lost.

    Comparison is on the compas JSON with `minimal=True` (guids of nested value
    geometry excluded, since those are regenerated by compas_pb's converters and
    carry no meaning). Parsed rather than textual comparison, so that an int
    widening to a float on a proto `double` field does not read as a difference.
    """
    other = roundtrip(obj)
    assert type(other) is type(obj)
    assert json.loads(json_dumps(other, minimal=True)) == json.loads(json_dumps(obj, minimal=True))
    assert str(other.guid) == str(obj.guid)
    assert other._name == obj._name
    return other


@pytest.fixture
def outline():
    return Polyline([Point(0, 0, 0), Point(1000, 0, 0), Point(1000, 1000, 0), Point(0, 1000, 0), Point(0, 0, 0)])


def test_beam_roundtrip():
    beam = Beam(Frame.worldXY(), length=5000.0, width=100.0, height=200.0, name="a_beam")
    other = assert_lossless(beam)
    assert other.length == beam.length
    assert other.width == beam.width
    assert other.frame == beam.frame


def test_beam_unnamed_stays_unnamed():
    beam = Beam(Frame.worldXY(), length=1.0, width=0.1, height=0.1)
    assert assert_lossless(beam)._name is None


def test_beam_from_centerline_roundtrip():
    beam = Beam.from_centerline(Line(Point(0, 0, 0), Point(3000, 0, 0)), width=100.0, height=200.0)
    assert_lossless(beam)


def test_beam_attributes_roundtrip():
    """Arbitrary kwargs land in `attributes` and are merged into __data__."""
    beam = Beam(Frame.worldXY(), length=1.0, width=0.1, height=0.1, category="rafter", index=7)
    other = assert_lossless(beam)
    assert other.attributes["category"] == "rafter"
    assert other.attributes["index"] == 7


def test_beam_double_precision_is_exact():
    beam = Beam(Frame.worldXY(), length=1234.56789012345, width=0.1 + 0.2, height=1e-7)
    other = roundtrip(beam)
    assert other.length == beam.length
    assert other.width == beam.width
    assert other.height == beam.height


def test_plate_geometry_roundtrip(outline):
    assert_lossless(Plate.from_outline_thickness(outline, 20.0).plate_geometry)


def test_plate_roundtrip(outline):
    plate = Plate.from_outline_thickness(outline, 20.0)
    other = assert_lossless(plate)
    assert other.plate_geometry.thickness == plate.plate_geometry.thickness


def test_panel_roundtrip(outline):
    panel = Panel.from_outline_thickness(outline, 50.0)
    other = assert_lossless(panel)
    assert other.type == panel.type


def test_panel_with_layer_structure_roundtrip(outline):
    panel = Panel.from_outline_thickness(outline, 50.0)
    panel.layer_structure = LayerStructure([
        LayerDefinition("exterior", 10.0),
        LayerDefinition("core", 30.0),
        LayerDefinition("interior", 10.0),
    ])
    other = assert_lossless(panel)
    assert [d.name for d in other.layer_structure.layer_defs] == ["exterior", "core", "interior"]


def test_layer_structure_roundtrip():
    assert_lossless(LayerStructure([LayerDefinition("core", 30.0)]))


def test_layer_definition_nested_roundtrip():
    nested = LayerDefinition("core", 30.0, sublayer_defs=[LayerDefinition("inner", 15.0)])
    other = assert_lossless(nested)
    assert other.sublayer_defs[0].name == "inner"


def test_opening_roundtrip(outline):
    panel = Panel.from_outline_thickness(outline, 50.0)
    opening = Opening.from_outline_panel(
        Polyline([Point(100, 100, 0), Point(400, 100, 0), Point(400, 400, 0), Point(100, 400, 0), Point(100, 100, 0)]),
        panel,
    )
    assert_lossless(opening)
