from itertools import combinations

from compas.data import Data
from compas.geometry import Point
from compas.geometry import distance_point_line
from compas.tolerance import TOL

from compas_timber.errors import BeamJoiningError
from compas_timber.utils import distance_segment_segment_points

from .solver import JointTopology


def location_from_centerlines(beams):
    """Compute the approximate joint location from two beam centerlines.

    Returns the closest point between the two centerlines, or the midpoint
    between them when the beams are skew (non-intersecting).

    Parameters
    ----------
    beams : list(:class:`~compas_timber.elements.Beam`)
        A list of two beams for which to calculate the joint location.

    Returns
    -------
    :class:`~compas.geometry.Point`

    """
    if len(beams) != 2:
        raise ValueError(
            "Automatic location calculation only works for joints connecting 2 elements. "
            "Please set the location manually or implement a custom location calculation for your joint type."
        )
    beam_a, beam_b = beams
    distance, point_a, point_b = distance_segment_segment_points(beam_a.centerline, beam_b.centerline)
    point_a, point_b = Point(*point_a), Point(*point_b)
    if not TOL.is_zero(distance):
        return (point_a + point_b) / 2.0
    return point_a


class Joint(Data):
    """Base class for a joint connecting two beams.

    This is a base class and should not be instantiated directly.
    Use the `create()` class method of the respective implementation of `Joint` instead.

    Parameters
    ----------
    topology : literal, one of :class:`JointTopology`
        The topology by which the two elements connected with this joint interact.
    location : :class:`~compas.geometry.Point`
        The estimated location of the interaction point of the two elements connected with this joint.

    Attributes
    ----------
    name : str
        The name of the joint. Corresponds to the class name.
    elements : tuple(:class:`~compas_model.elements.Element`)
        The elements joined by this joint.
    generated_elements : list(:class:`~compas_model.elements.Element`)
        A list of elements that were generated by this joint.
    ends : dict(str, str)
        Maps the GUID of each element to ``start`` or ``end``, depending on which end of the element is connected by this joint.
    interactions : list(tuple(:class:`~compas_model.elements.Element`, :class:`~compas_model.elements.Element`))
        A list of tuples containing the elements that are interacting with each other through this joint.
    features : list(:class:`~compas_timber.fabrication.BTLxProcessing`)
        A list of features that were added to the elements by this joint.
    topology : literal, one of :class:`JointTopology`
        The topology by which the two elements connected with this joint interact.
    location : :class:`~compas.geometry.Point`
        The estimated location of the interaction point of the two elements connected with this joint.
    """

    SUPPORTED_TOPOLOGY = JointTopology.TOPO_UNKNOWN
    MIN_ELEMENT_COUNT = 2
    MAX_ELEMENT_COUNT = 2

    def __init__(self, elements=None, topology=None, location=None, name=None, element_guids=None, **kwargs):
        super().__init__(name=name)
        # filter out Nones — subclasses pass e.g. elements=(None, None) during deserialization
        elements = tuple(e for e in (elements or ()) if e is not None)

        if elements:
            # Normal creation: elements are live objects, derive guids from them
            self._elements = elements
            self.element_guids = tuple(str(e.guid) for e in elements)
        elif element_guids:
            # Deserialization: only guids available, elements are restored later
            # by TimberModel.__from_data__() via restore_elements_from_keys()
            self._elements = ()
            self.element_guids = tuple(element_guids)
        else:
            raise ValueError("Joint requires either elements or element_guids.")

        self._topology = topology if topology is not None else JointTopology.TOPO_UNKNOWN
        self._location = location

    @property
    def __data__(self):
        # type: () -> dict
        return {"name": self.name, "topology": self._topology, "location": self._location, "element_guids": self.element_guids}

    def __repr__(self):
        return '{}(name="{}")'.format(self.__class__.__name__, self.name)

    @property
    def elements(self):
        return self._elements

    @property
    def element_a(self):
        return self._elements[0] if len(self._elements) > 0 else None

    @property
    def element_b(self):
        return self._elements[1] if len(self._elements) > 1 else None

    @property
    def topology(self):
        return self._topology

    @topology.setter
    def topology(self, value):
        self._topology = value or JointTopology.TOPO_UNKNOWN

    @property
    def location(self):
        # all(()) == True, so we need to check len(self.elements) as well to avoid calculating location for joints without elements
        if self._location is None and all(self.elements) and len(self.elements) == 2:
            self._location = location_from_centerlines(self.elements)

        if self._location is None:
            raise ValueError("Location of the joint could not be determined. Please set it manually.")

        return self._location

    @location.setter
    def location(self, value):
        """Set the location of the joint."""
        if not isinstance(value, Point):
            raise TypeError("Location must be a Point.")
        self._location = value

    @property
    def generated_elements(self):
        return []

    @property
    def ends(self):
        # TODO: this may be obsolete, don't see it used anywhere, consider removing
        self._ends = {}
        for index, beam in enumerate(self.elements):
            if distance_point_line(beam.centerline.start, self.elements[index - 1].centerline) < distance_point_line(beam.centerline.end, self.elements[index - 1].centerline):
                self._ends[str(beam.guid)] = "start"
            else:
                self._ends[str(beam.guid)] = "end"
        return self._ends

    @property
    def interactions(self):
        interactions = []
        for pair in combinations(self.elements, 2):
            interactions.append((pair[0], pair[1]))
        return interactions

    @classmethod
    def element_count_complies(cls, elements):
        """Checks if the number of elements complies with the joint's requirements.

        Parameters
        ----------
        elements : list(:class:`~compas_model.elements.Element`)
            The elements to be checked.

        Returns
        -------
        bool

        """
        if cls.MAX_ELEMENT_COUNT:
            return len(elements) >= cls.MIN_ELEMENT_COUNT and len(elements) <= cls.MAX_ELEMENT_COUNT
        else:
            return len(elements) >= cls.MIN_ELEMENT_COUNT

    def add_features(self):
        """Adds the features defined by this joint to affected beam(s).

        Raises
        ------
        :class:`~compas_timber.connections.BeamJoiningError`
            Should be raised whenever the joint was not able to calculate the features to be applied to the beams.

        """
        raise NotImplementedError

    def add_extensions(self):
        """Adds the extensions defined by this joint to affected beam(s).
        This is optional and should only be implemented by joints that require it.

        Notes
        -----
        Extensions are added to all beams before the features are added.

        Raises
        ------
        :class:`~compas_timber.connections.BeamJoiningError`
            Should be raised whenever the joint was not able to calculate the extensions to be applied to the beams.

        """
        pass

    def restore_elements_from_keys(self, model):
        """Restores the reference to the elements associated with this joint.

        During serialization, :class:`compas_timber.elements.Beam` objects
        are serialized by :class:`compas_timber.model.Model`. To avoid circular references, Joint only stores the keys
        of the respective elements.

        This method is called by :class:`compas_timber.model.TimberModel` during de-serialization to restore the references.
        Since the roles of the elements are joint specific (e.g. main/cross beam) this method should be implemented by
        the concrete implementation.

        Examples
        --------
        See :class:`compas_timber.connections.TButtJoint`.

        """
        self._elements = tuple(model.element_by_guid(guid) for guid in self.element_guids)
        self._set_unset_attributes()

        # TODO add fasteners to this as well? should we have a separate self.fastener_guids property?

    def _set_unset_attributes(self):
        """Sets attributes that are not set during initialization but are required for the joint to function properly.

        This is necessary because during de-serialization, the constructor is not called and therefore these attributes
        are not set. This method is called by `restore_elements_from_keys()` after the elements have been restored.

        This method should be implemented by the concrete implementation of `Joint` if there are any such attributes.

        """
        pass

    @classmethod
    def create(cls, model, *elements, **kwargs):
        """Creates an instance of this joint and creates the new connection in `model`.

        `elements` are expected to have been added to `model` before calling this method.

        This code does not verify that the given elements are adjacent and/or lie in a topology which allows connecting
        them. This is the responsibility of the calling code.

        Parameters
        ----------
        model : :class:`~compas_timber.model.TimberModel`
            The model to which the elements and this joint belong.
        *elements : :class:`~compas_model.elements.Element`
            The elements to be connected by this joint. The number of elements must comply with the `Joint` class's
            `MIN_ELEMENT_COUNT` and `MAX_ELEMENT_COUNT` attributes.
        **kwargs : dict
            Additional keyword arguments that are passed to the joint's constructor.

        Returns
        -------
        :class:`compas_timber.connections.Joint`
            The instance of the created joint.

        """

        joint = cls(*elements, **kwargs)
        model.add_joint(joint)
        return joint

    @classmethod
    def promote_cluster(cls, model, cluster, reordered_elements=None, **kwargs):
        """Creates an instance of this joint from a cluster of elements.

        Parameters
        ----------
        model : :class:`~compas_timber.model.TimberModel`
            The model to which the elements and this joint belong.
        cluster : :class:`~compas_model.clusters.Cluster`
            The cluster containing the elements to be connected by this joint.
        reordered_elements : list(:class:`~compas_model.elements.Element`), optional
            The elements to be connected by this joint. If not provided, the elements of the cluster will be used.
            This is used to explicitly define the element order.
        **kwargs : dict
            Additional keyword arguments that are passed to the joint's constructor.

        Returns
        -------
        :class:`compas_timber.connections.Joint`
            The instance of the created joint.

        """
        if reordered_elements:
            if set(reordered_elements) != cluster.elements:
                raise BeamJoiningError(cls, "Elements of the joint candidate must match the provided elements.", [e.blank for e in reordered_elements])
        if len(cluster.joints) == 1:
            elements = reordered_elements or cluster.joints[0].elements
            return cls.promote_joint_candidate(model, cluster.joints[0], reordered_elements=elements, **kwargs)
        else:
            elements = reordered_elements or list(cluster.elements)
        return cls.create(model, *elements, **kwargs)

    @classmethod
    def promote_joint_candidate(cls, model, candidate, reordered_elements=None, **kwargs):
        """Creates an instance of this joint from a joint candidate.

        Parameters
        ----------
        model : :class:`~compas_timber.model.TimberModel`
            The model to which the elements and this joint belong.
        candidate : :class:`~compas_timber.connections.JointCandidate`
            The joint candidate to be converted.
        reordered_elements : list(:class:`~compas_model.elements.Element`), optional
            The elements to be connected by this joint. If not provided, the elements of the generic joint will be used.
            This is used to explicitly define the element order.
        **kwargs : dict
            Additional keyword arguments that are passed to the joint's constructor.

        Returns
        -------
        :class:`compas_timber.connections.Joint`
            The instance of the created joint.

        """
        if reordered_elements:
            assert set(reordered_elements) == set(candidate.elements), "Elements of the generic joint must match the provided elements."
            elements = reordered_elements
        else:
            elements = candidate.elements
        kwargs.update({"topology": candidate.topology, "location": candidate.location})  # pass topology, distance and location from candidate
        joint = cls.create(model, *elements, **kwargs)
        return joint

    @classmethod
    def check_elements_compatibility(cls, elements, raise_error=False):
        """Checks if the cluster of beams complies with the requirements for the Joint.

        Parameters
        ----------
        elements : list of :class:`~compas_timber.elements.Beam`
            The beams to check.
        raise_error : bool, optional
            If True, raises a `BeamJoiningError` if the requirements are not met.

        Returns
        -------
        bool
            True if the cluster complies with the requirements, False otherwise.

        """
        return True

    def point_centerline_towards_joint(self, beam):
        """
        Returns the centerline vector of beam_a pointing towards the joint with beam_b.

        Parameters
        ----------
        beam_a : :class:`~compas_timber.elements.Beam`
            The beam that attaches with one of its ends to the side of beam_b.
        beam_b : :class:`~compas_timber.elements.Beam`
            The other beam.

        Returns
        -------
        :class:`~compas.geometry.Vector`
            The centerline vector of beam_a pointing towards the joint with beam_b.
        """

        # find the orientation of beams's centerline so that it's pointing towards the joint
        # find the closest end
        end, _ = beam.endpoint_closest_to_point(self.location)
        if end == "start":
            centerline_vec = beam.centerline.vector * -1
        else:
            centerline_vec = beam.centerline.vector
        return centerline_vec
