from abc import ABC
from abc import abstractmethod

from compas.data import Data
from compas.geometry import Frame

from compas_timber.fasteners.fastener import Fastener


class JointFastener(Data, ABC):
    """
    A an abstract parent class for joints that uses fasteners. It provides the general methods and functionality of a joint that uses fasteners.

    Parameters
    ----------
    base_fastener : :class:`compas_timber.fasteners.Fastener`
        The base fastener that defines the type of fastener used in the joint.
        This fastener will be used as a template to create instances of the fastener for each target frame in the joint.
        The base fasenter can contains `sub-fasteners`. The base fasteners is not part of the joint it is a reference on how to initiate
        the fasteners that will participate in the joint. It is structured in a hierarchical structure between `base_fastener` and `dasteners`.

    Attributes
    ----------
    generated_elements : list
        A list of al the elements generated by the joint.
    fasteners : list[Fastener]
        A list of all the fasteners generated and participating in the joint.
    fasteners_interactions : list[tuple]
        A list of tuples describing the interactions between fasteners and beams and between fasteners and sub-fasteners in the joint. Each tuple contains a pair of
        elements that interact, needed to build the interaction graph of the `TimberModel`.

    """

    def __init__(self, base_fastener: Fastener, **kwargs):
        super().__init__(**kwargs)
        self.base_fastener = base_fastener
        self._fasteners = []
        if all(self.beams):
            self.place_fasteners_instances()

    @property
    def generated_elements(self):
        return self.fasteners

    @property
    def fasteners(self) -> list[Fastener]:
        """
        Returns all fasteners of the joint.

        Returns
        -------
        list[:class:`compas_timber.fasteners.Fastener`]
            A list of all fasteners in the joint.
        """
        fasteners = []
        for fastener in self._fasteners:
            fasteners.extend(fastener.find_all_nested_sub_fasteners())
        return fasteners

    @property
    def fasteners_interactions(self) -> list[tuple]:
        """
        Computes the interactions between fasteners and beams and fastener and sub-fastnert participating to the joint.
        """
        interactions = []
        if not hasattr(self, "beams"):
            raise AttributeError("The attribute 'beams' does not exist on this object.")

        # beam ---- fastener ---- beam
        for fastener in self._fasteners:
            for beam in self.beams:  # type: ignore
                interactions.append((beam, fastener))
            # fastener ---- sub_fastener ---- sub-fastener
            interactions.extend(fastener.compute_sub_fasteners_interactions())
        return interactions

    @abstractmethod
    def place_fasteners_instances(self):
        """
        Places new instances of the `base_fastener` at the target frames of the joint.
        """
        raise NotImplementedError("Subclasses of JointFastener must implement the place_fasteners_instances method.")

    @abstractmethod
    def compute_fastener_target_frames(self) -> list[Frame]:
        """
        Compute the target frames of the joint. The target frame is where the new instance of the fastener should be placed by `place_fasteners_instaces`.
        """
        raise NotImplementedError("Subclasses of JointFastener must implement the compute_fastener_target_frames method.")
